name: linting
on:
  push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11

      - name: pip install
        run: |
          pip install . ipykernel jupytext lifelines nbconvert pyflakes pylance pylint texoutparse &&
          rm -r build

      - name: pyflakes
        run: |
          python -m pyflakes .

      - name: pylint
        run: |
          python -m pylint .

      - name: convert notebooks
        run: |
          jupytext --sync docs/roc_picker/*.md docs/kombine/*.md

      - uses: jakebailey/pyright-action@v2.3.2
        with:
          version: 1.1.400