name: tests and docs
on:
  push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: pip install
        run: |
          pip install . ipykernel jupytext lifelines nbconvert pyflakes pylance pylint texoutparse &&
          rm -r build
      - name: pyflakes
        run: |
          python -m pyflakes .
      - name: pylint
        run: |
          python -m pylint .
      - name: convert notebooks
        run: |
          jupytext --sync docs/*.md
      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.400

      - name: Install Gurobi
        run: |
          wget https://packages.gurobi.com/10.0/gurobi10.0.3_linux64.tar.gz
          tar -xvzf gurobi10.0.3_linux64.tar.gz
          echo "export GUROBI_HOME=$PWD/gurobi1003/linux64" >> $GITHUB_ENV
          echo "$PWD/gurobi1003/linux64/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$PWD/gurobi1003/linux64/lib" >> $GITHUB_ENV
          cd gurobi1003/linux64
          python setup.py install
          cd ../..

      #to get the license:
      #go to https://www.gurobi.com/
      #request a WLS license (free for academics)
      #download the license file, which will be named gurobi.lic
      #and contain the WLSACCESSID, WLSSECRET, and LICENSEID
      #then set the secrets in the repo settings:
      #GUROBI_WLSACCESSID, GUROBI_WLSSECRET, and GUROBI_LICENSEID
      - name: Configure Gurobi WLS license
        run: |
          cat <<EOF > ~/gurobi.lic
          WLSACCESSID=${{ secrets.GUROBI_WLSACCESSID }}
          WLSSECRET=${{ secrets.GUROBI_WLSSECRET }}
          LICENSEID=${{ secrets.GUROBI_LICENSEID }}
          EOF

      - name: test code in README
        run: |
          startlinenumber="$(grep -n import README.md | sed "s/:.*//")"
          endlinenumber="$(expr "$startlinenumber" + "$(sed -n 26,1000p README.md | grep -n '```' | sed "s/:.*//")" - 2)"
          sed -n "${startlinenumber},${endlinenumber}p" README.md | python

      - name: test notebooks
        run: |
          jupyter nbconvert --execute --to html -- docs/*.ipynb

      - name: test discrete optimization module
        run: |
          python -m test.test_discrete_optimization
      - name: discrete unit test
        run: |
          python -m test.test_discrete
      - name: systematics MC unit test
        run: |
          python -m test.test_systematics_mc
      - name: KM likelihood unit test
        run: |
          python -m test.test_km_likelihood
      #no need for a separate step for continuous distributions unit test
      #because it's run by compile_plots.sh

      - name: Compile plots
        run: |
          ./docs/compile_plots.sh
      - name: Compile docs
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs
          root_file: 02_rocpicker.tex
          latexmk_use_xelatex: true
      - name: Compile docs
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs
          root_file: 08_kaplan_meier_paper.tex
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: docs
          path: |
            docs/02_rocpicker.pdf
            docs/08_kaplan_meier_paper.pdf
            docs/*.html
      - name: Check latex log
        run: |
          python .github/workflows/checklog.py docs/*.log  --ignore-regex "Macro 'volume[+]number' undefined." --ignore-regex 'Underfull \\vbox \(badness (10000|1648)\) has occurred' --ignore-regex 'Option .hyperindex. has already been used' --ignore-regex 'Missing driver name\.'
