name: tests and docs
on:
  push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: pip install
        run: |
          pip install . ipykernel jupytext nbconvert pyflakes texoutparse
      - name: pyflakes
        run: |
          python -m pyflakes .
      - name: pylint
        run: |
          python -m pylint .

      - name: test code in README
        run: |
          startlinenumber="$(grep -n import README.md | sed "s/:.*//")"
          endlinenumber="$(expr "$startlinenumber" + "$(sed -n 26,1000p README.md | grep -n '```' | sed "s/:.*//")" - 2)"
          sed -n "${startlinenumber},${endlinenumber}p" README.md | python

      - name: convert notebooks
        run: |
          jupytext --sync docs/*.md
      - name: test notebooks
        run: |
          jupyter nbconvert --execute --to html -- docs/*.ipynb

      - name: discrete unit test
        run: |
          python -m test.test_discrete

      - name: Compile plots
        run: |
          ./docs/compile_plots.sh
      - name: Compile docs
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs
          root_file: 02_rocpicker.tex
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: docs
          path: |
            docs/02_rocpicker.pdf
            docs/*.html
      - name: Check latex log
        run: |
          python .github/workflows/checklog.py docs/02_rocpicker.log
