name: test KoMbine
on:
  push
jobs:
  test_kombine:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11

      - name: pip install
        run: |
          pip install . ipykernel jupytext lifelines nbconvert pyflakes pylint texoutparse &&
          rm -r build

      - name: Install Gurobi
        run: |
          wget https://packages.gurobi.com/10.0/gurobi10.0.3_linux64.tar.gz
          tar -xvzf gurobi10.0.3_linux64.tar.gz
          echo "export GUROBI_HOME=$PWD/gurobi1003/linux64" >> $GITHUB_ENV
          echo "$PWD/gurobi1003/linux64/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=$PWD/gurobi1003/linux64/lib" >> $GITHUB_ENV
          cd gurobi1003/linux64
          python setup.py install
          cd ../..

      #to get the license:
      #go to https://www.gurobi.com/
      #request a WLS license (free for academics)
      #download the license file, which will be named gurobi.lic
      #and contain the WLSACCESSID, WLSSECRET, and LICENSEID
      #then set the secrets in the repo settings:
      #GUROBI_WLSACCESSID, GUROBI_WLSSECRET, and GUROBI_LICENSEID
      - name: Configure Gurobi WLS license
        run: |
          cat <<EOF > ~/gurobi.lic
          WLSACCESSID=${{ secrets.GUROBI_WLSACCESSID }}
          WLSSECRET=${{ secrets.GUROBI_WLSSECRET }}
          LICENSEID=${{ secrets.GUROBI_LICENSEID }}
          EOF

      - name: test KoMbine code in README
        run: |
          # Extract and modify the KoMbine example from README and test it
          startlinenumber="$(grep -n "from kombine.datacard import Datacard" README.md | sed "s/:.*//")"
          endlinenumber="$(sed -n "${startlinenumber},1000p" README.md | grep -n '```' | head -1 | sed "s/:.*//")"
          endlinenumber="$(expr "$startlinenumber" + "$endlinenumber" - 2)"
          # Modify the datacard path to work with the test structure and remove plotting
          sed -n "${startlinenumber},${endlinenumber}p" README.md | sed 's|test/kombine/datacards/simple_examples/simple_km_few_deaths.txt|test/kombine/datacards/simple_examples/simple_km_few_deaths.txt|' | sed '/\.plot()/d' | python

      - name: test discrete optimization module
        run: |
          python -m test.kombine.test_discrete_optimization

      - name: KM likelihood unit test
        run: |
          python -m test.kombine.test_km_likelihood

      - name: continuous distributions test
        run: |
          python test/kombine/test_continuous_distributions.py

      - name: convert KoMbine notebooks
        run: |
          jupytext --sync docs/kombine/*.md

      - name: test KoMbine notebooks
        run: |
          jupyter nbconvert --execute --to html -- docs/kombine/*.ipynb

      - name: Compile KM plots
        run: |
          ./docs/kombine/compile_km_plots.sh

      - name: Compile KoMbine docs
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs/kombine
          root_file: 08_kaplan_meier_paper.tex

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: kombine_docs
          path: |
            docs/kombine/08_kaplan_meier_paper.pdf
            docs/kombine/*.html

      - name: Check latex log
        run: |
          python .github/workflows/checklog.py docs/kombine/*.log  --ignore-regex "Macro 'volume[+]number' undefined." --ignore-regex 'Underfull \\vbox \(badness (10000|2189)\) has occurred' --ignore-regex 'Option .hyperindex. has already been used' --ignore-regex 'Missing driver name\.'